x = set()  # we can use .add() or update function as well 
numbers1 = int(input("Enter no. "))
x.add(numbers1)
numbers2 = int(input("Enter no. "))
x.add(numbers2)
numbers3 = int(input("Enter no. "))
x.add(numbers3)
numbers4 = int(input("Enter no. "))
x.add(numbers4)
numbers5 = int(input("Enter no. "))
x.add(numbers5)
numbers6 = int(input("Enter no. "))
x.add(numbers6)
numbers7 = int(input("Enter no. "))
x.add(numbers7)
numbers8 = int(input("Enter no. "))
x.add(numbers8)
# x.update(numbers1, numbers2, numbers3, numbers4, numbers5, numbers6, numbers7, numbers8)
print(x)